# Generated by Django 4.2.11 on 2024-04-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('base_currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('BGN', 'Bulgarian Lev'), ('CZK', 'Czech Republic Korun'), ('DKK', 'Danish Krone'), ('GBP', 'British Pound Sterling'), ('HUF', 'Hungarian Forint'), ('PLN', 'Polish Zloty'), ('RON', 'Romanian Leu'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('ISK', 'Icelandic Króna'), ('NOK', 'Norwegian Krone'), ('HRK', 'Croatian Kuna'), ('RUB', 'Russian Ruble'), ('TRY', 'Turkish Lira'), ('AUD', 'Australian Dollar'), ('BRL', 'Brazilian Real'), ('CAD', 'Canadian Dollar'), ('CNY', 'Chinese Yuan'), ('HKD', 'Hong Kong Dollar'), ('IDR', 'Indonesian Rupiah'), ('ILS', 'Israeli New Sheqel'), ('INR', 'Indian Rupee'), ('KRW', 'South Korean Won'), ('MXN', 'Mexican Peso'), ('MYR', 'Malaysian Ringgit'), ('NZD', 'New Zealand Dollar'), ('PHP', 'Philippine Peso'), ('SGD', 'Singapore Dollar'), ('THB', 'Thai Baht'), ('ZAR', 'South African Rand')], max_length=5)),
                ('target_currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('BGN', 'Bulgarian Lev'), ('CZK', 'Czech Republic Korun'), ('DKK', 'Danish Krone'), ('GBP', 'British Pound Sterling'), ('HUF', 'Hungarian Forint'), ('PLN', 'Polish Zloty'), ('RON', 'Romanian Leu'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('ISK', 'Icelandic Króna'), ('NOK', 'Norwegian Krone'), ('HRK', 'Croatian Kuna'), ('RUB', 'Russian Ruble'), ('TRY', 'Turkish Lira'), ('AUD', 'Australian Dollar'), ('BRL', 'Brazilian Real'), ('CAD', 'Canadian Dollar'), ('CNY', 'Chinese Yuan'), ('HKD', 'Hong Kong Dollar'), ('IDR', 'Indonesian Rupiah'), ('ILS', 'Israeli New Sheqel'), ('INR', 'Indian Rupee'), ('KRW', 'South Korean Won'), ('MXN', 'Mexican Peso'), ('MYR', 'Malaysian Ringgit'), ('NZD', 'New Zealand Dollar'), ('PHP', 'Philippine Peso'), ('SGD', 'Singapore Dollar'), ('THB', 'Thai Baht'), ('ZAR', 'South African Rand')], max_length=5)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.BigIntegerField()),
                ('message', models.CharField(max_length=150)),
                ('is_seen', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('payment_received', 'Payment Received'), ('payment_request_received', 'Payment Request Received'), ('payment_request_result', 'Payment Request Result')], default='payment_received', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
