# Generated by Django 4.2.11 on 2024-05-02 10:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payapp', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TranscationRequest',
            new_name='PaymentRequest',
        ),
    ]
