# Generated by Django 4.2.11 on 2024-05-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_rename_transcationrequest_paymentrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExchangeRate',
            new_name='ConversionRate',
        ),
    ]
