# Generated by Django 4.2.11 on 2024-05-03 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_rename_exchangerate_conversionrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversionRate',
        ),
    ]
