# Generated by Django 4.2.11 on 2024-05-03 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0006_payment_delete_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
    ]
