# Generated by Django 4.2.11 on 2024-05-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0007_alter_payment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='object_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('payment_received', 'Payment Received'), ('payment_request_received', 'Payment Request Received'), ('payment_request_result', 'Payment Request Result')], default='payment_received', max_length=50),
        ),
    ]
